spring:
  application:
    name: ai-service
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:password}

server:
  port: 8084

# Google Gemini AI Configuration
gemini:
  api:
    key: ${GEMINI_API_KEY:your-api-key}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent

# RabbitMQ Queue Configuration
rabbitmq:
  queues:
    name: activity-analysis-queue
  exchanges:
    name: activity-exchange
  routing-keys:
    activity-analysis: activity.analysis
    
# Flat properties for @Value injection (matching Java @Value annotations)
rabbitmq.queue.name: activity-analysis-queue
rabbitmq.exchanges.name: activity-exchange
rabbitmq.routing.key: activity.analysis

logging:
  level:
    com.fitness.aiservice: DEBUG
